import Foundation
import SwiftUI

// MARK: - Spectromorphological symbol typology (Thoresen-inspired, simplified)

enum MassKind: String, Codable, CaseIterable, Identifiable {
    case pitched
    case dystonic
    case complex

    var id: String { rawValue }

    var labelSV: String {
        switch self {
        case .pitched: return "Tonalt (pitched)"
        case .dystonic: return "Dystoniskt / blandat"
        case .complex: return "Komplext (otonalt)"
        }
    }
}

enum EnergyKind: String, Codable, CaseIterable, Identifiable {
    case impulse
    case sustained
    case iterated
    case composite
    case accumulation
    case vacillating

    var id: String { rawValue }

    var labelSV: String {
        switch self {
        case .impulse: return "Impuls"
        case .sustained: return "Uthållet"
        case .iterated: return "Itererat"
        case .composite: return "Sammansatt"
        case .accumulation: return "Ackumulation"
        case .vacillating: return "Vacklande"
        }
    }
}

enum ScoreSymbolKind: String, Codable, CaseIterable, Identifiable {
    case pitchedImpulse
    case pitchedSustained
    case complexImpulse
    case complexSustained
    case iterated
    case accumulation
    case variable
    case stratified

    var id: String { rawValue }

    var mass: MassKind {
        switch self {
        case .pitchedImpulse, .pitchedSustained, .variable: return .pitched
        case .complexImpulse, .complexSustained, .accumulation: return .complex
        case .iterated, .stratified: return .dystonic
        }
    }

    var energy: EnergyKind {
        switch self {
        case .pitchedImpulse, .complexImpulse: return .impulse
        case .pitchedSustained, .complexSustained, .stratified: return .sustained
        case .iterated: return .iterated
        case .accumulation: return .accumulation
        case .variable: return .vacillating
        }
    }

    var labelSV: String {
        switch self {
        case .pitchedImpulse: return "Tonimpuls"
        case .pitchedSustained: return "Ton uthållen"
        case .complexImpulse: return "Komplex impuls"
        case .complexSustained: return "Komplex uthållen"
        case .iterated: return "Itererad"
        case .accumulation: return "Ackumulation"
        case .variable: return "Variabel / glidande"
        case .stratified: return "Stratifierad"
        }
    }
}

// MARK: - Score document

struct ScoreDocument: Codable, Identifiable {
    var id: UUID
    var sourceName: String
    var duration: Double
    var createdAt: Date
    var objects: [ScoreObject]
    var timeFields: [TimeField]
    var dynamicForms: [DynamicForm]
    var brackets: [ScoreBracket]

    init(
        id: UUID = UUID(),
        sourceName: String,
        duration: Double,
        createdAt: Date = Date(),
        objects: [ScoreObject] = [],
        timeFields: [TimeField] = [],
        dynamicForms: [DynamicForm] = [],
        brackets: [ScoreBracket] = []
    ) {
        self.id = id
        self.sourceName = sourceName
        self.duration = duration
        self.createdAt = createdAt
        self.objects = objects
        self.timeFields = timeFields
        self.dynamicForms = dynamicForms
        self.brackets = brackets
    }
}

struct ScoreObject: Codable, Identifiable, Hashable {
    var id: UUID
    var label: String
    var start: Double
    var end: Double
    var lane: Int
    var symbol: ScoreSymbolKind
    var filled: Bool
    var note: String
    var autoGenerated: Bool

    var duration: Double { max(0, end - start) }

    init(
        id: UUID = UUID(),
        label: String,
        start: Double,
        end: Double,
        lane: Int = 0,
        symbol: ScoreSymbolKind,
        filled: Bool = true,
        note: String = "",
        autoGenerated: Bool = false
    ) {
        self.id = id
        self.label = label
        self.start = start
        self.end = end
        self.lane = lane
        self.symbol = symbol
        self.filled = filled
        self.note = note
        self.autoGenerated = autoGenerated
    }
}

struct TimeField: Codable, Identifiable, Hashable {
    var id: UUID
    var start: Double
    var end: Double
    var name: String
    var colorHex: String

    init(
        id: UUID = UUID(),
        start: Double,
        end: Double,
        name: String,
        colorHex: String = "#F5E6A8"
    ) {
        self.id = id
        self.start = start
        self.end = end
        self.name = name
        self.colorHex = colorHex
    }

    var color: Color {
        Color(hex: colorHex) ?? Color.yellow.opacity(0.25)
    }
}

struct DynamicForm: Codable, Identifiable, Hashable {
    enum Shape: String, Codable {
        case crescendo
        case diminuendo
        case swell
        case plateau
    }

    var id: UUID
    var start: Double
    var end: Double
    var shape: Shape
    var intensity: Double

    init(
        id: UUID = UUID(),
        start: Double,
        end: Double,
        shape: Shape,
        intensity: Double = 1
    ) {
        self.id = id
        self.start = start
        self.end = end
        self.shape = shape
        self.intensity = intensity
    }
}

struct ScoreBracket: Codable, Identifiable, Hashable {
    var id: UUID
    var start: Double
    var end: Double
    var label: String

    init(id: UUID = UUID(), start: Double, end: Double, label: String = "") {
        self.id = id
        self.start = start
        self.end = end
        self.label = label
    }
}

// MARK: - Color helper

extension Color {
    init?(hex: String) {
        var s = hex.trimmingCharacters(in: .whitespacesAndNewlines)
        if s.hasPrefix("#") { s.removeFirst() }
        guard s.count == 6 || s.count == 8, let value = UInt64(s, radix: 16) else { return nil }
        let r, g, b, a: Double
        if s.count == 8 {
            a = Double((value >> 24) & 0xFF) / 255
            r = Double((value >> 16) & 0xFF) / 255
            g = Double((value >> 8) & 0xFF) / 255
            b = Double(value & 0xFF) / 255
        } else {
            a = 1
            r = Double((value >> 16) & 0xFF) / 255
            g = Double((value >> 8) & 0xFF) / 255
            b = Double(value & 0xFF) / 255
        }
        self.init(.sRGB, red: r, green: g, blue: b, opacity: a)
    }
}

// MARK: - Persistence

enum ScoreStore {
    static func url(beside audioOrCSV: URL) -> URL {
        audioOrCSV.deletingPathExtension().appendingPathExtension("wosscore.json")
    }

    static func save(_ doc: ScoreDocument, beside url: URL) throws -> URL {
        let out = self.url(beside: url)
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
        encoder.dateEncodingStrategy = .iso8601
        try encoder.encode(doc).write(to: out, options: .atomic)
        return out
    }

    static func load(beside url: URL) -> ScoreDocument? {
        let path = self.url(beside: url)
        guard let data = try? Data(contentsOf: path) else { return nil }
        let decoder = JSONDecoder()
        decoder.dateDecodingStrategy = .iso8601
        return try? decoder.decode(ScoreDocument.self, from: data)
    }
}
