import Foundation

enum ScoreBuilder {
    struct FeatureBundle {
        var times: [Double]
        var rms: [Double]
        var centroid: [Double]
        var zcr: [Double]
        var novelty: [Double]
        var mfcc1: [Double]?
    }

    /// Bygg score från feature-kurvor (förfinad onset/offset-analys).
    static func build(
        sourceName: String,
        duration: Double,
        times: [Double],
        rms: [Double],
        centroid: [Double],
        zcr: [Double],
        novelty: [Double],
        mfcc1: [Double]? = nil
    ) -> ScoreDocument {
        build(
            sourceName: sourceName,
            duration: duration,
            features: FeatureBundle(
                times: times,
                rms: rms,
                centroid: centroid,
                zcr: zcr,
                novelty: novelty,
                mfcc1: mfcc1
            )
        )
    }

    static func build(from series: [FeatureSeries], sourceName: String, duration: Double) -> ScoreDocument {
        func values(_ kind: FeatureSeries.Kind) -> [Double]? {
            series.first { $0.kind == kind }?.points.map(\.value)
        }
        func times(for kind: FeatureSeries.Kind) -> [Double]? {
            series.first { $0.kind == kind }?.points.map(\.time)
        }

        guard
            let t = times(for: .rms) ?? times(for: .novelty),
            let rms = values(.rms),
            let centroid = values(.centroid),
            let zcr = values(.zcr),
            let novelty = values(.novelty)
        else {
            return ScoreDocument(sourceName: sourceName, duration: duration)
        }

        return build(
            sourceName: sourceName,
            duration: max(duration, t.last ?? 0),
            features: FeatureBundle(
                times: t,
                rms: rms,
                centroid: centroid,
                zcr: zcr,
                novelty: novelty,
                mfcc1: values(.mfcc1)
            )
        )
    }

    static func build(sourceName: String, duration: Double, features: FeatureBundle) -> ScoreDocument {
        let smoothedNovelty = smooth(features.novelty, window: 5)
        let smoothedRMS = smooth(features.rms, window: 5)
        let onsets = detectOnsets(
            times: features.times,
            novelty: smoothedNovelty,
            rms: smoothedRMS,
            duration: duration
        )

        var rawObjects: [RawObject] = []
        for (i, onset) in onsets.enumerated() {
            let nextOnset = (i + 1 < onsets.count) ? onsets[i + 1] : duration
            guard let obj = buildObject(
                onset: onset,
                nextOnset: nextOnset,
                features: features,
                smoothedRMS: smoothedRMS,
                smoothedNovelty: smoothedNovelty
            ) else { continue }
            rawObjects.append(obj)
        }

        rawObjects = mergeTinyGaps(rawObjects, minGap: 0.18)
        rawObjects = dropSilent(rawObjects)

        let piece = PieceStats(features: features)
        for i in rawObjects.indices {
            rawObjects[i].symbol = classify(rawObjects[i], piece: piece)
            rawObjects[i].lane = lane(for: rawObjects[i].meanCentroid, piece: piece)
            rawObjects[i].filled = rawObjects[i].meanRMS >= piece.rmsMedian * 0.55
        }

        assignFamilyLabels(&rawObjects)

        let peakRMS = rawObjects.map(\.meanRMS).max() ?? 1
        let objects: [ScoreObject] = rawObjects.map { raw in
            ScoreObject(
                label: raw.label,
                start: raw.start,
                end: raw.end,
                lane: raw.lane,
                symbol: raw.symbol,
                filled: raw.filled,
                note: autoNote(raw),
                autoGenerated: true,
                rmsEnergy: peakRMS > 1e-12 ? min(1, raw.meanRMS / peakRMS) : 0.5
            )
        }

        return ScoreDocument(
            sourceName: sourceName,
            duration: duration,
            objects: objects,
            timeFields: suggestTimeFields(duration: duration, objects: objects, rms: features.rms, times: features.times),
            dynamicForms: suggestDynamicForms(times: features.times, rms: features.rms, objects: objects),
            brackets: suggestBrackets(objects: objects)
        )
    }

    /// Fyll i / uppdatera `rmsEnergy` från feature-RMS (för äldre .wosscore.json och manuella objekt).
    static func enrichEnergies(_ doc: ScoreDocument, from series: [FeatureSeries]) -> ScoreDocument {
        guard let rmsSeries = series.first(where: { $0.kind == .rms }),
              !rmsSeries.points.isEmpty else { return doc }
        let times = rmsSeries.points.map(\.time)
        let rms = rmsSeries.points.map(\.value)
        var out = doc
        var energies = [Double](repeating: 0, count: out.objects.count)
        for i in out.objects.indices {
            let obj = out.objects[i]
            let slice = indices(times: times, start: obj.start, end: obj.end)
            energies[i] = slice.isEmpty ? 0 : average(rms, slice)
        }
        let peak = energies.max() ?? 0
        for i in out.objects.indices {
            if peak > 1e-12 {
                out.objects[i].rmsEnergy = min(1, energies[i] / peak)
            } else if out.objects[i].rmsEnergy <= 0 {
                out.objects[i].rmsEnergy = 0.5
            }
        }
        return out
    }

    static func rmsEnergy(
        start: Double,
        end: Double,
        from series: [FeatureSeries]
    ) -> Double {
        guard let rmsSeries = series.first(where: { $0.kind == .rms }),
              !rmsSeries.points.isEmpty else { return 1 }
        let times = rmsSeries.points.map(\.time)
        let rms = rmsSeries.points.map(\.value)
        let slice = indices(times: times, start: start, end: end)
        let local = slice.isEmpty ? 0 : average(rms, slice)
        let peak = rms.max() ?? 0
        guard peak > 1e-12 else { return 0.5 }
        return min(1, local / peak)
    }

    /// Slå ihop ny auto-analys med manuella objekt/fält/former (behåller manuella oförändrade).
    static func mergeKeepingManual(auto: ScoreDocument, previous: ScoreDocument) -> ScoreDocument {
        let manualObjects = previous.objects.filter { !$0.autoGenerated }
        var combined = auto.objects + manualObjects
        combined.sort { $0.start < $1.start }

        let manualFields = previous.timeFields.filter { !$0.autoGenerated }
        var fields = auto.timeFields + manualFields
        fields.sort { $0.start < $1.start }

        let manualForms = previous.dynamicForms.filter { !$0.autoGenerated }
        var forms = auto.dynamicForms + manualForms
        forms.sort { $0.start < $1.start }

        var doc = auto
        doc.objects = combined
        doc.timeFields = fields
        doc.dynamicForms = forms
        return doc
    }

    // MARK: - Raw object

    private struct RawObject {
        var start: Double
        var end: Double
        var meanRMS: Double
        var meanZCR: Double
        var meanCentroid: Double
        var stdCentroid: Double
        var meanNovelty: Double
        var peakNovelty: Double
        var attackRatio: Double
        var meanMFCC: Double?
        var symbol: ScoreSymbolKind = .pitchedSustained
        var lane: Int = 1
        var filled: Bool = true
        var label: String = "?"

        var duration: Double { end - start }
    }

    private struct PieceStats {
        let zcrMedian: Double
        let zcrP75: Double
        let centroidMedian: Double
        let centroidMad: Double
        let noveltyMedian: Double
        let noveltyP80: Double
        let rmsMedian: Double

        init(features: FeatureBundle) {
            zcrMedian = median(features.zcr)
            zcrP75 = percentile(features.zcr, 0.75)
            centroidMedian = median(features.centroid)
            centroidMad = mad(features.centroid, around: centroidMedian)
            noveltyMedian = median(features.novelty)
            noveltyP80 = percentile(features.novelty, 0.80)
            rmsMedian = median(features.rms)
        }
    }

    // MARK: - Onset / offset

    private static func detectOnsets(
        times: [Double],
        novelty: [Double],
        rms: [Double],
        duration: Double
    ) -> [Double] {
        guard times.count > 4 else { return [0] }

        let novMed = median(novelty)
        let novMad = max(mad(novelty, around: novMed), 1e-6)
        // Adaptiv tröskel: mer robust än max*0.35
        let threshold = max(novMed + 2.8 * novMad, percentile(novelty, 0.78))

        var candidates: [(time: Double, strength: Double)] = []
        var lastAccepted = -10.0
        let minGap = 0.35

        for i in 2..<(novelty.count - 2) {
            let v = novelty[i]
            let isPeak = v >= novelty[i - 1] && v >= novelty[i + 1]
                && v >= novelty[i - 2] && v >= novelty[i + 2]
            guard isPeak, v >= threshold else { continue }

            // Kräv att RMS inte är total tystnad
            if rms[i] < max(median(rms) * 0.08, 0.0015) { continue }

            let t = times[i]
            if t - lastAccepted < minGap {
                // Behåll starkare peak i närheten
                if let last = candidates.last, v > last.strength {
                    candidates[candidates.count - 1] = (t, v)
                    lastAccepted = t
                }
                continue
            }
            candidates.append((t, v))
            lastAccepted = t
        }

        var onsets = candidates.map(\.time)
        if onsets.isEmpty {
            // Fallback: dela upp i jämna fönster om novelty är flat
            let step = max(2.0, duration / 8)
            var t = 0.0
            while t < duration - 0.5 {
                onsets.append(t)
                t += step
            }
        }
        if onsets.first ?? 1 > 0.25 { onsets.insert(0, at: 0) }
        return onsets
    }

    private static func buildObject(
        onset: Double,
        nextOnset: Double,
        features: FeatureBundle,
        smoothedRMS: [Double],
        smoothedNovelty: [Double]
    ) -> RawObject? {
        let hardEnd = nextOnset - 0.04
        guard hardEnd > onset + 0.08 else { return nil }

        let sliceAll = indices(times: features.times, start: onset, end: hardEnd)
        guard !sliceAll.isEmpty else { return nil }

        // Offset: när RMS faller under andel av lokal peak, med hysterés
        let localPeakRMS = sliceAll.map { smoothedRMS[$0] }.max() ?? 0
        let releaseThresh = max(localPeakRMS * 0.28, median(features.rms) * 0.12)

        var end = hardEnd
        let searchStart = indices(times: features.times, start: onset + 0.12, end: hardEnd)
        var belowCount = 0
        for idx in searchStart {
            if smoothedRMS[idx] < releaseThresh {
                belowCount += 1
                if belowCount >= 3 {
                    end = features.times[idx]
                    break
                }
            } else {
                belowCount = 0
            }
        }

        // Om objektet annars skulle äta nästan hela vägen till nästa onset, låt det sluta tidigare
        // om novelty är låg i svansen.
        let tail = indices(times: features.times, start: max(onset + 0.2, end - 0.4), end: end)
        if !tail.isEmpty {
            let tailNov = average(smoothedNovelty, tail)
            if tailNov < median(smoothedNovelty) * 0.7, end - onset > 2.5 {
                // trimma långa lågenergi-svansar
                if let lastActive = sliceAll.last(where: { smoothedRMS[$0] >= releaseThresh * 1.1 }) {
                    end = max(onset + 0.15, features.times[lastActive])
                }
            }
        }

        end = min(end, hardEnd)
        guard end - onset >= 0.12 else { return nil }

        let slice = indices(times: features.times, start: onset, end: end)
        guard slice.count >= 2 else { return nil }

        let meanRMS = average(features.rms, slice)
        let meanZCR = average(features.zcr, slice)
        let meanCent = average(features.centroid, slice)
        let stdCent = stddev(features.centroid, slice)
        let meanNov = average(features.novelty, slice)
        let peakNov = slice.map { features.novelty[$0] }.max() ?? 0

        // Attack: RMS första 15% vs peak
        let attackCount = max(1, slice.count / 7)
        let attackRMS = average(features.rms, Array(slice.prefix(attackCount)))
        let attackRatio = localPeakRMS > 1e-9 ? attackRMS / localPeakRMS : 0

        let mfcc: Double? = {
            guard let mfcc1 = features.mfcc1, mfcc1.count == features.times.count else { return nil }
            return average(mfcc1, slice)
        }()

        return RawObject(
            start: onset,
            end: end,
            meanRMS: meanRMS,
            meanZCR: meanZCR,
            meanCentroid: meanCent,
            stdCentroid: stdCent,
            meanNovelty: meanNov,
            peakNovelty: peakNov,
            attackRatio: attackRatio,
            meanMFCC: mfcc
        )
    }

    private static func mergeTinyGaps(_ objects: [RawObject], minGap: Double) -> [RawObject] {
        guard !objects.isEmpty else { return [] }
        var out: [RawObject] = [objects[0]]
        for obj in objects.dropFirst() {
            var prev = out[out.count - 1]
            if obj.start - prev.end < minGap,
               abs((obj.meanZCR) - prev.meanZCR) < 0.04,
               abs((obj.meanCentroid) - prev.meanCentroid) < 350 {
                prev.end = max(prev.end, obj.end)
                prev.meanRMS = (prev.meanRMS + obj.meanRMS) / 2
                prev.meanZCR = (prev.meanZCR + obj.meanZCR) / 2
                prev.meanCentroid = (prev.meanCentroid + obj.meanCentroid) / 2
                prev.stdCentroid = max(prev.stdCentroid, obj.stdCentroid)
                prev.meanNovelty = max(prev.meanNovelty, obj.meanNovelty)
                prev.peakNovelty = max(prev.peakNovelty, obj.peakNovelty)
                if let a = prev.meanMFCC, let b = obj.meanMFCC {
                    prev.meanMFCC = (a + b) / 2
                }
                out[out.count - 1] = prev
            } else {
                out.append(obj)
            }
        }
        return out
    }

    private static func dropSilent(_ objects: [RawObject]) -> [RawObject] {
        objects.filter { $0.meanRMS > 0.002 || $0.peakNovelty > 0.08 }
    }

    // MARK: - Classification

    private static func classify(_ obj: RawObject, piece: PieceStats) -> ScoreSymbolKind {
        let noisy = obj.meanZCR > max(piece.zcrP75 * 0.92, piece.zcrMedian * 1.25)
        let veryNoisy = obj.meanZCR > max(piece.zcrP75 * 1.15, 0.14)
        let short = obj.duration < 0.75
        let impulsive = obj.attackRatio < 0.55 && obj.duration < 1.4
        let variable = obj.stdCentroid > max(piece.centroidMad * 3.2, 380)
        let dense = obj.meanNovelty > piece.noveltyP80 || obj.peakNovelty > piece.noveltyP80 * 1.35
        let sustained = obj.duration >= 0.9 && obj.attackRatio > 0.45

        if dense && veryNoisy { return .accumulation }
        if dense && !short { return .iterated }
        if variable && sustained { return .variable }
        if variable && short { return .variable }

        // Stratifierad: uthållen energi med bred centroid-spridning men inte extrem ZCR
        if sustained && obj.stdCentroid > max(piece.centroidMad * 2.4, 280) && !veryNoisy {
            return .stratified
        }

        if impulsive || short {
            return noisy ? .complexImpulse : .pitchedImpulse
        }
        return noisy ? .complexSustained : .pitchedSustained
    }

    private static func lane(for centroid: Double, piece: PieceStats) -> Int {
        // Relativt styckets median, inte absolut max
        let delta = centroid - piece.centroidMedian
        let scale = max(piece.centroidMad, 80)
        if delta > scale * 1.1 { return 0 }      // ljusare / högre
        if delta < -scale * 1.1 { return 2 }     // mörkare / lägre
        return 1
    }

    private static func assignFamilyLabels(_ objects: inout [RawObject]) {
        let letters = Array("ABCDEFGHIJKLMNOPQRSTUVWXYZ").map(String.init)
        var familyCenters: [(symbol: ScoreSymbolKind, mfcc: Double?, centroid: Double, letter: String)] = []
        var letterIndex = 0

        for i in objects.indices {
            let obj = objects[i]
            var matchedLetter: String?

            for center in familyCenters {
                // Samma symboltyp + liknande klang → samma familj
                guard center.symbol == obj.symbol else { continue }
                let centClose = abs(center.centroid - obj.meanCentroid) < 500
                let mfccClose: Bool = {
                    guard let a = center.mfcc, let b = obj.meanMFCC else { return centClose }
                    return abs(a - b) < 8.0
                }()
                if centClose && mfccClose {
                    matchedLetter = center.letter
                    break
                }
            }

            if let matchedLetter {
                // Primtecken för återkomst: A, A′, A″ …
                let count = objects.prefix(i).filter { $0.label.hasPrefix(matchedLetter) }.count
                objects[i].label = count == 0 ? matchedLetter : matchedLetter + String(repeating: "′", count: min(count, 3))
            } else {
                let letter = letters[letterIndex % letters.count]
                letterIndex += 1
                familyCenters.append(
                    (obj.symbol, obj.meanMFCC, obj.meanCentroid, letter)
                )
                objects[i].label = letter
            }
        }
    }

    private static func autoNote(_ raw: RawObject) -> String {
        var parts = [
            "auto: \(raw.symbol.labelSV)",
            String(format: "ZCR %.3f", raw.meanZCR),
            String(format: "cent %.0f Hz", raw.meanCentroid),
            String(format: "%.2f s", raw.duration)
        ]
        if let mfcc = raw.meanMFCC {
            parts.append(String(format: "MFCC₁ %.1f", mfcc))
        }
        return parts.joined(separator: " · ")
    }

    // MARK: - Time fields / forms / brackets

    private static func suggestTimeFields(
        duration: Double,
        objects: [ScoreObject],
        rms: [Double],
        times: [Double]
    ) -> [TimeField] {
        guard duration > 2, !objects.isEmpty else {
            return [TimeField(start: 0, end: duration, name: "Fält 1", colorHex: "#F5E6A8", autoGenerated: true)]
        }

        // Brytpunkter: större tysta luckor mellan objekt
        var cuts: [Double] = [0]
        for i in 0..<(objects.count - 1) {
            let gap = objects[i + 1].start - objects[i].end
            if gap > 1.4 {
                cuts.append((objects[i].end + objects[i + 1].start) / 2)
            }
        }
        cuts.append(duration)
        cuts = Array(Set(cuts.map { ($0 * 10).rounded() / 10 })).sorted()

        // Om få luckor: använd RMS-energi i tredjedelar
        if cuts.count <= 2, duration > 8 {
            cuts = [0, duration / 3, 2 * duration / 3, duration]
        }

        let colors = ["#F5E6A8", "#DCC6E8", "#C9E4DE", "#F2D0C9", "#D9E2F3"]
        var fields: [TimeField] = []
        for i in 0..<(cuts.count - 1) {
            let a = cuts[i]
            let b = cuts[i + 1]
            guard b - a > 0.4 else { continue }
            fields.append(
                TimeField(
                    start: a,
                    end: b,
                    name: "Fält \(fields.count + 1)",
                    colorHex: colors[fields.count % colors.count],
                    autoGenerated: true
                )
            )
        }
        return fields.isEmpty
            ? [TimeField(start: 0, end: duration, name: "Fält 1", colorHex: "#F5E6A8", autoGenerated: true)]
            : fields
    }

    private static func suggestDynamicForms(
        times: [Double],
        rms: [Double],
        objects: [ScoreObject]
    ) -> [DynamicForm] {
        var forms: [DynamicForm] = []
        for obj in objects {
            let slice = indices(times: times, start: obj.start, end: obj.end)
            guard slice.count > 5 else { continue }
            let n = slice.count
            let a = average(rms, Array(slice.prefix(n / 3)))
            let b = average(rms, Array(slice[n / 3 ..< (2 * n / 3)]))
            let c = average(rms, Array(slice.suffix(n / 3)))

            if b > a * 1.25 && b > c * 1.15 {
                forms.append(DynamicForm(start: obj.start, end: obj.end, shape: .swell, intensity: 1, autoGenerated: true))
            } else if c > a * 1.3 {
                forms.append(DynamicForm(start: obj.start, end: obj.end, shape: .crescendo, intensity: 1, autoGenerated: true))
            } else if a > c * 1.3 {
                forms.append(DynamicForm(start: obj.start, end: obj.end, shape: .diminuendo, intensity: 1, autoGenerated: true))
            } else if obj.duration > 1.8 {
                forms.append(DynamicForm(start: obj.start, end: obj.end, shape: .plateau, intensity: 0.7, autoGenerated: true))
            }
        }
        return forms
    }

    private static func suggestBrackets(objects: [ScoreObject]) -> [ScoreBracket] {
        guard objects.count >= 2 else { return [] }
        var brackets: [ScoreBracket] = []
        var i = 0
        var group = 1
        while i < objects.count {
            let startObj = objects[i]
            var j = i
            while j + 1 < objects.count && objects[j + 1].start - objects[j].end < 1.0 {
                j += 1
            }
            if j > i {
                brackets.append(ScoreBracket(start: startObj.start, end: objects[j].end, label: "fras \(group)"))
                group += 1
            }
            i = j + 1
        }
        return brackets
    }

    // MARK: - Stats helpers

    private static func indices(times: [Double], start: Double, end: Double) -> [Int] {
        times.indices.filter { times[$0] >= start && times[$0] < end }
    }

    private static func average(_ values: [Double], _ idxs: [Int]) -> Double {
        guard !idxs.isEmpty else { return 0 }
        return idxs.reduce(0.0) { $0 + values[$1] } / Double(idxs.count)
    }

    private static func stddev(_ values: [Double], _ idxs: [Int]) -> Double {
        guard idxs.count > 1 else { return 0 }
        let mean = average(values, idxs)
        let varSum = idxs.reduce(0.0) {
            let d = values[$1] - mean
            return $0 + d * d
        }
        return sqrt(varSum / Double(idxs.count))
    }

    private static func smooth(_ values: [Double], window: Int) -> [Double] {
        guard window > 1, values.count >= window else { return values }
        let r = window / 2
        return values.indices.map { i in
            let lo = max(0, i - r)
            let hi = min(values.count - 1, i + r)
            let slice = values[lo...hi]
            return slice.reduce(0, +) / Double(slice.count)
        }
    }

    private static func median(_ values: [Double]) -> Double {
        guard !values.isEmpty else { return 0 }
        let s = values.sorted()
        let m = s.count / 2
        if s.count % 2 == 0 {
            return (s[m - 1] + s[m]) / 2
        }
        return s[m]
    }

    private static func mad(_ values: [Double], around center: Double) -> Double {
        guard !values.isEmpty else { return 0 }
        return median(values.map { abs($0 - center) })
    }

    private static func percentile(_ values: [Double], _ p: Double) -> Double {
        guard !values.isEmpty else { return 0 }
        let s = values.sorted()
        let idx = min(s.count - 1, max(0, Int((Double(s.count - 1) * p).rounded())))
        return s[idx]
    }
}
