import Foundation

enum ScoreBuilder {
    /// Build a first-pass spectromorphological score from feature series + novelty peaks.
    static func build(
        sourceName: String,
        duration: Double,
        times: [Double],
        rms: [Double],
        centroid: [Double],
        zcr: [Double],
        novelty: [Double]
    ) -> ScoreDocument {
        let boundaries = peakBoundaries(times: times, novelty: novelty, duration: duration)
        var objects: [ScoreObject] = []
        let labels = Array("ABCDEFGHIJKLMNOPQRSTUVWXYZ").map(String.init)

        for (idx, pair) in zip(boundaries, boundaries.dropFirst()).enumerated() {
            let start = pair.0
            let end = pair.1
            guard end - start > 0.12 else { continue }

            let slice = indices(times: times, start: start, end: end)
            guard !slice.isEmpty else { continue }

            let meanZCR = average(zcr, slice)
            let meanCent = average(centroid, slice)
            let stdCent = stddev(centroid, slice)
            let meanRMS = average(rms, slice)
            let meanNov = average(novelty, slice)
            let dur = end - start

            let symbol = classify(
                duration: dur,
                meanZCR: meanZCR,
                centroidStd: stdCent,
                meanNovelty: meanNov
            )

            // Skip near-silent segments
            if meanRMS < 0.004 && meanNov < 0.05 { continue }

            let label = labels[idx % labels.count]
            objects.append(
                ScoreObject(
                    label: label,
                    start: start,
                    end: end,
                    lane: lane(for: meanCent, maxCentroid: centroid.max() ?? 4000),
                    symbol: symbol,
                    filled: true,
                    note: autoNote(symbol: symbol, zcr: meanZCR, dur: dur),
                    autoGenerated: true
                )
            )
        }

        let fields = suggestTimeFields(duration: duration, objects: objects)
        let forms = suggestDynamicForms(times: times, rms: rms, objects: objects)
        let brackets = suggestBrackets(objects: objects)

        return ScoreDocument(
            sourceName: sourceName,
            duration: duration,
            objects: objects,
            timeFields: fields,
            dynamicForms: forms,
            brackets: brackets
        )
    }

    // MARK: - Segmentation

    private static func peakBoundaries(times: [Double], novelty: [Double], duration: Double) -> [Double] {
        guard !times.isEmpty else { return [0, duration] }
        let maxN = novelty.max() ?? 1
        let threshold = max(maxN * 0.35, 0.15)
        var peaks: [Double] = [0]
        var lastPeakTime = -1.0
        let minGap = 0.6

        for i in 1..<(novelty.count - 1) {
            let v = novelty[i]
            if v >= threshold && v >= novelty[i - 1] && v >= novelty[i + 1] {
                let t = times[i]
                if t - lastPeakTime >= minGap {
                    peaks.append(t)
                    lastPeakTime = t
                }
            }
        }
        if let last = peaks.last, duration - last > 0.3 {
            peaks.append(duration)
        } else if peaks.last != duration {
            peaks.append(duration)
        }
        return peaks
    }

    private static func indices(times: [Double], start: Double, end: Double) -> [Int] {
        times.indices.filter { times[$0] >= start && times[$0] < end }
    }

    private static func average(_ values: [Double], _ idxs: [Int]) -> Double {
        guard !idxs.isEmpty else { return 0 }
        return idxs.reduce(0.0) { $0 + values[$1] } / Double(idxs.count)
    }

    private static func stddev(_ values: [Double], _ idxs: [Int]) -> Double {
        guard idxs.count > 1 else { return 0 }
        let mean = average(values, idxs)
        let varSum = idxs.reduce(0.0) {
            let d = values[$1] - mean
            return $0 + d * d
        }
        return sqrt(varSum / Double(idxs.count))
    }

    private static func classify(
        duration: Double,
        meanZCR: Double,
        centroidStd: Double,
        meanNovelty: Double
    ) -> ScoreSymbolKind {
        let noisy = meanZCR > 0.12
        let short = duration < 0.85
        let variable = centroidStd > 450
        let dense = meanNovelty > 0.8

        if dense && noisy { return .accumulation }
        if dense { return .iterated }
        if variable { return .variable }
        if short && noisy { return .complexImpulse }
        if short && !noisy { return .pitchedImpulse }
        if !short && noisy { return .complexSustained }
        return .pitchedSustained
    }

    private static func lane(for centroid: Double, maxCentroid: Double) -> Int {
        let norm = maxCentroid > 0 ? centroid / maxCentroid : 0
        if norm < 0.33 { return 2 }
        if norm < 0.66 { return 1 }
        return 0
    }

    private static func autoNote(symbol: ScoreSymbolKind, zcr: Double, dur: Double) -> String {
        "auto: \(symbol.labelSV), ZCR \(String(format: "%.3f", zcr)), \(String(format: "%.2f", dur)) s"
    }

    private static func suggestTimeFields(duration: Double, objects: [ScoreObject]) -> [TimeField] {
        guard duration > 1 else { return [] }
        if objects.count < 4 {
            return [
                TimeField(start: 0, end: duration, name: "Fält 1", colorHex: "#F5E6A8")
            ]
        }
        let mid = duration * 0.55
        return [
            TimeField(start: 0, end: mid, name: "Fält 1", colorHex: "#F5E6A8"),
            TimeField(start: mid, end: duration, name: "Fält 2", colorHex: "#DCC6E8")
        ]
    }

    private static func suggestDynamicForms(
        times: [Double],
        rms: [Double],
        objects: [ScoreObject]
    ) -> [DynamicForm] {
        var forms: [DynamicForm] = []
        for obj in objects.prefix(12) {
            let slice = indices(times: times, start: obj.start, end: obj.end)
            guard slice.count > 3 else { continue }
            let first = average(rms, Array(slice.prefix(slice.count / 3)))
            let last = average(rms, Array(slice.suffix(slice.count / 3)))
            if last > first * 1.35 {
                forms.append(DynamicForm(start: obj.start, end: obj.end, shape: .crescendo, intensity: 1))
            } else if first > last * 1.35 {
                forms.append(DynamicForm(start: obj.start, end: obj.end, shape: .diminuendo, intensity: 1))
            } else if obj.duration > 2 {
                forms.append(DynamicForm(start: obj.start, end: obj.end, shape: .plateau, intensity: 0.7))
            }
        }
        return forms
    }

    private static func suggestBrackets(objects: [ScoreObject]) -> [ScoreBracket] {
        guard objects.count >= 2 else { return [] }
        var brackets: [ScoreBracket] = []
        var i = 0
        var group = 1
        while i < objects.count {
            let startObj = objects[i]
            var j = i
            while j + 1 < objects.count && objects[j + 1].start - objects[j].end < 1.2 {
                j += 1
            }
            if j > i {
                brackets.append(
                    ScoreBracket(
                        start: startObj.start,
                        end: objects[j].end,
                        label: "fras \(group)"
                    )
                )
                group += 1
            }
            i = j + 1
        }
        return brackets
    }
}
