import Foundation
import SwiftUI

// MARK: - Spectromorphological symbol typology (Thoresen-inspired, simplified)

enum MassKind: String, Codable, CaseIterable, Identifiable {
    case pitched
    case dystonic
    case complex

    var id: String { rawValue }

    var labelSV: String {
        switch self {
        case .pitched: return "Tonalt (pitched)"
        case .dystonic: return "Dystoniskt / blandat"
        case .complex: return "Komplext (otonalt)"
        }
    }
}

enum EnergyKind: String, Codable, CaseIterable, Identifiable {
    case impulse
    case sustained
    case iterated
    case composite
    case accumulation
    case vacillating

    var id: String { rawValue }

    var labelSV: String {
        switch self {
        case .impulse: return "Impuls"
        case .sustained: return "Uthållet"
        case .iterated: return "Itererat"
        case .composite: return "Sammansatt"
        case .accumulation: return "Ackumulation"
        case .vacillating: return "Vacklande"
        }
    }
}

enum ScoreSymbolKind: String, Codable, CaseIterable, Identifiable {
    case pitchedImpulse
    case pitchedSustained
    case complexImpulse
    case complexSustained
    case iterated
    case accumulation
    case variable
    case stratified

    var id: String { rawValue }

    var mass: MassKind {
        switch self {
        case .pitchedImpulse, .pitchedSustained, .variable: return .pitched
        case .complexImpulse, .complexSustained, .accumulation: return .complex
        case .iterated, .stratified: return .dystonic
        }
    }

    var energy: EnergyKind {
        switch self {
        case .pitchedImpulse, .complexImpulse: return .impulse
        case .pitchedSustained, .complexSustained, .stratified: return .sustained
        case .iterated: return .iterated
        case .accumulation: return .accumulation
        case .variable: return .vacillating
        }
    }

    var labelSV: String {
        switch self {
        case .pitchedImpulse: return "Tonimpuls"
        case .pitchedSustained: return "Ton uthållen"
        case .complexImpulse: return "Komplex impuls"
        case .complexSustained: return "Komplex uthållen"
        case .iterated: return "Itererad"
        case .accumulation: return "Ackumulation"
        case .variable: return "Variabel / glidande"
        case .stratified: return "Stratifierad"
        }
    }
}

// MARK: - Score document

struct ScoreDocument: Codable, Identifiable {
    var id: UUID
    var sourceName: String
    var duration: Double
    var createdAt: Date
    var objects: [ScoreObject]
    var timeFields: [TimeField]
    var dynamicForms: [DynamicForm]
    var brackets: [ScoreBracket]

    init(
        id: UUID = UUID(),
        sourceName: String,
        duration: Double,
        createdAt: Date = Date(),
        objects: [ScoreObject] = [],
        timeFields: [TimeField] = [],
        dynamicForms: [DynamicForm] = [],
        brackets: [ScoreBracket] = []
    ) {
        self.id = id
        self.sourceName = sourceName
        self.duration = duration
        self.createdAt = createdAt
        self.objects = objects
        self.timeFields = timeFields
        self.dynamicForms = dynamicForms
        self.brackets = brackets
    }
}



struct ScoreObject: Codable, Identifiable, Hashable {
    var id: UUID
    var label: String
    var start: Double
    var end: Double
    var lane: Int
    var symbol: ScoreSymbolKind
    var filled: Bool
    var note: String
    var autoGenerated: Bool
    /// Relative loudness within the piece, 0…1 (for object-visibility filter).
    var rmsEnergy: Double
    /// Nashville number when tonal pitch is available (e.g. "1", "b3", "5").
    var nashville: String
    /// Pitch class 0…11 (C=0), or -1 if unknown.
    var pitchClass: Int

    var duration: Double { max(0, end - start) }

    init(
        id: UUID = UUID(),
        label: String,
        start: Double,
        end: Double,
        lane: Int = 0,
        symbol: ScoreSymbolKind,
        filled: Bool = true,
        note: String = "",
        autoGenerated: Bool = false,
        rmsEnergy: Double = 1,
        nashville: String = "",
        pitchClass: Int = -1
    ) {
        self.id = id
        self.label = label
        self.start = start
        self.end = end
        self.lane = lane
        self.symbol = symbol
        self.filled = filled
        self.note = note
        self.autoGenerated = autoGenerated
        self.rmsEnergy = min(1, max(0, rmsEnergy))
        self.nashville = nashville
        self.pitchClass = pitchClass
    }

    enum CodingKeys: String, CodingKey {
        case id, label, start, end, lane, symbol, filled, note, autoGenerated, rmsEnergy, nashville, pitchClass
    }

    init(from decoder: Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        id = try c.decodeIfPresent(UUID.self, forKey: .id) ?? UUID()
        label = try c.decode(String.self, forKey: .label)
        start = try c.decode(Double.self, forKey: .start)
        end = try c.decode(Double.self, forKey: .end)
        lane = try c.decodeIfPresent(Int.self, forKey: .lane) ?? 0
        symbol = try c.decode(ScoreSymbolKind.self, forKey: .symbol)
        filled = try c.decodeIfPresent(Bool.self, forKey: .filled) ?? true
        note = try c.decodeIfPresent(String.self, forKey: .note) ?? ""
        autoGenerated = try c.decodeIfPresent(Bool.self, forKey: .autoGenerated) ?? false
        rmsEnergy = try c.decodeIfPresent(Double.self, forKey: .rmsEnergy) ?? 1
        nashville = try c.decodeIfPresent(String.self, forKey: .nashville) ?? ""
        pitchClass = try c.decodeIfPresent(Int.self, forKey: .pitchClass) ?? -1
    }
}

struct TimeField: Codable, Identifiable, Hashable {
    var id: UUID
    var start: Double
    var end: Double
    var name: String
    var colorHex: String
    var autoGenerated: Bool

    static let paletteColors = ["#F5E6A8", "#DCC6E8", "#C9E4DE", "#F2D0C9", "#D9E2F3", "#E8D5C4"]

    init(
        id: UUID = UUID(),
        start: Double,
        end: Double,
        name: String,
        colorHex: String = "#F5E6A8",
        autoGenerated: Bool = false
    ) {
        self.id = id
        self.start = start
        self.end = end
        self.name = name
        self.colorHex = colorHex
        self.autoGenerated = autoGenerated
    }

    var color: Color {
        Color(hex: colorHex) ?? Color.yellow.opacity(0.25)
    }

    var duration: Double { max(0, end - start) }

    enum CodingKeys: String, CodingKey {
        case id, start, end, name, colorHex, autoGenerated
    }

    init(from decoder: Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        id = try c.decodeIfPresent(UUID.self, forKey: .id) ?? UUID()
        start = try c.decode(Double.self, forKey: .start)
        end = try c.decode(Double.self, forKey: .end)
        name = try c.decode(String.self, forKey: .name)
        colorHex = try c.decodeIfPresent(String.self, forKey: .colorHex) ?? "#F5E6A8"
        autoGenerated = try c.decodeIfPresent(Bool.self, forKey: .autoGenerated) ?? true
    }
}

struct DynamicForm: Codable, Identifiable, Hashable {
    enum Shape: String, Codable, CaseIterable, Identifiable {
        case crescendo
        case diminuendo
        case swell
        case plateau

        var id: String { rawValue }

        var labelSV: String {
            switch self {
            case .crescendo: return "Crescendo"
            case .diminuendo: return "Diminuendo"
            case .swell: return "Svällning"
            case .plateau: return "Platå"
            }
        }
    }

    var id: UUID
    var start: Double
    var end: Double
    var shape: Shape
    var intensity: Double
    var autoGenerated: Bool

    init(
        id: UUID = UUID(),
        start: Double,
        end: Double,
        shape: Shape,
        intensity: Double = 1,
        autoGenerated: Bool = false
    ) {
        self.id = id
        self.start = start
        self.end = end
        self.shape = shape
        self.intensity = intensity
        self.autoGenerated = autoGenerated
    }

    var duration: Double { max(0, end - start) }

    enum CodingKeys: String, CodingKey {
        case id, start, end, shape, intensity, autoGenerated
    }

    init(from decoder: Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        id = try c.decodeIfPresent(UUID.self, forKey: .id) ?? UUID()
        start = try c.decode(Double.self, forKey: .start)
        end = try c.decode(Double.self, forKey: .end)
        shape = try c.decode(Shape.self, forKey: .shape)
        intensity = try c.decodeIfPresent(Double.self, forKey: .intensity) ?? 1
        autoGenerated = try c.decodeIfPresent(Bool.self, forKey: .autoGenerated) ?? true
    }
}

struct ScoreBracket: Codable, Identifiable, Hashable {
    var id: UUID
    var start: Double
    var end: Double
    var label: String

    init(id: UUID = UUID(), start: Double, end: Double, label: String = "") {
        self.id = id
        self.start = start
        self.end = end
        self.label = label
    }
}

// MARK: - Color helper

extension Color {
    init?(hex: String) {
        var s = hex.trimmingCharacters(in: .whitespacesAndNewlines)
        if s.hasPrefix("#") { s.removeFirst() }
        guard s.count == 6 || s.count == 8, let value = UInt64(s, radix: 16) else { return nil }
        let r, g, b, a: Double
        if s.count == 8 {
            a = Double((value >> 24) & 0xFF) / 255
            r = Double((value >> 16) & 0xFF) / 255
            g = Double((value >> 8) & 0xFF) / 255
            b = Double(value & 0xFF) / 255
        } else {
            a = 1
            r = Double((value >> 16) & 0xFF) / 255
            g = Double((value >> 8) & 0xFF) / 255
            b = Double(value & 0xFF) / 255
        }
        self.init(.sRGB, red: r, green: g, blue: b, opacity: a)
    }
}

// MARK: - Persistence

enum ScoreStore {
    static func url(beside audioOrCSV: URL) -> URL {
        audioOrCSV.deletingPathExtension().appendingPathExtension("wosscore.json")
    }

    static func save(_ doc: ScoreDocument, beside url: URL) throws -> URL {
        let out = self.url(beside: url)
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
        encoder.dateEncodingStrategy = .iso8601
        try encoder.encode(doc).write(to: out, options: .atomic)
        return out
    }

    static func load(beside url: URL) -> ScoreDocument? {
        let path = self.url(beside: url)
        guard let data = try? Data(contentsOf: path) else { return nil }
        let decoder = JSONDecoder()
        decoder.dateDecodingStrategy = .iso8601
        return try? decoder.decode(ScoreDocument.self, from: data)
    }
}
